import { createRouter, createWebHistory } from "vue-router";

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
scrollBehavior(to) {
if(to.hash){
    return { el: "#app", top: 0, behavior: "smooth" };
}
  },
  routes: [
    {
      path: "/",
      name: "index",
      component: () => import("../views/home/Home.vue"),
      meta: { layout: "layout" },
    },
    {
      path: "/index-2",
      name: "index-2",
      component: () => import("../views/home/Home2.vue"),
      meta: { layout7: "layout7" },
    },
    {
      path: "/index-3",
      name: "index-3",
      component: () => import("../views/home/Home3.vue"),
      meta: { layout: "layout" },
    },
    {
      path: "/shop-standard",
      name: "Shop Standard",
      component: () => import("../views/shop/ShopStandard.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-list",
      name: "Shop List",
      component: () => import("../views/shop/ShopList.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-with-category",
      name: "Shop With Category",
      component: () => import("../views/shop/ShopWithCategory.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-filters-top-bar",
      name: "Shop Filters Top Bar",
      component: () => import("../views/shop/ShopFiltersTopBar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-sidebar",
      name: "Shop Sidebar",
      component: () => import("../views/shop/ShopSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-style-1",
      name: "Shop Style 1",
      component: () => import("../views/shop/ShopStyle1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-style-2",
      name: "Shop Style 2",
      component: () => import("../views/shop/ShopStyle2.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/product-default",
      name: "Product Default",
      component: () => import("../views/shop/ProductDefault.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/product-thumbnail",
      name: "Product Thumbnail",
      component: () => import("../views/shop/ProductThumbnail.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/product-grid-media",
      name: "Product Grid Media",
      component: () => import("../views/shop/ProductGridMedia.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/product-carousel",
      name: "ProductCarousel",
      component: () => import("../views/shop/ProductCarousel.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/product-full-width",
      name: "ProductFullWidth",
      component: () => import("../views/shop/ProductFullWidth.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-wishlist",
      name: "ShopWishlist",
      component: () => import("../views/shop/ShopWishlist.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-cart",
      name: "shop-cart",
      component: () => import("../views/shop/ShopCart.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-checkout",
      name: "ShopCheckout",
      component: () => import("../views/shop/ShopCheckout.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/shop-compare",
      name: "ShopCompare",
      component: () => import("../views/shop/ShopCompare.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/shop-order-tracking",
      name: "ShopOrderTracking",
      component: () => import("../views/shop/ShopOrderTracking.vue"),
      meta: { layout: "layout" },
    },
    {
      path: "/login",
      name: "Login",
      component: () => import("../views/shop/Login.vue"),
      meta: { layout: "layout" },
    },
    {
      path: "/registration",
      name: "Registration",
      component: () => import("../views/shop/Registration.vue"),
      meta: { layout: "layout" },
    },
    {
      path: "/forget-password",
      name: "ForgetPassword",
      component: () => import("../views/shop/ForgetPassword.vue"),
      meta: { layout: "layout" },
    },
    {
      path: "/blog-dark-2-column",
      name: "Blog Dark 2 Column",
      component: () => import("../views/blog/BlogDark2Column.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-dark-2-column-sidebar",
      name: "Blog Dark 2 Column Sidebar",
      component: () => import("../views/blog/BlogDark2ColumnSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-dark-3-column",
      name: "Blog Dark 3 Column",
      component: () => import("../views/blog/BlogDark3Column.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-dark-half-image",
      name: "Blog Dark Half Image",
      component: () => import("../views/blog/BlogDarkHalfImage.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-light-2-column",
      name: "Blog Light 2 Column",
      component: () => import("../views/blog/BlogLight2Column.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-light-2-column-sidebar",
      name: "Blog Light 2 Column Sidebar",
      component: () => import("../views/blog/BlogLight2ColumnSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-light-half-image",
      name: "Blog Light Half Image",
      component: () => import("../views/blog/BlogLightHalfImage.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-exclusive",
      name: "BlogExclusive",
      component: () => import("../views/blog/BlogExclusive.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-left-sidebar",
      name: "Blog Left Sidebar",
      component: () => import("../views/blog/BlogLeftSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-right-sidebar",
      name: "Blog Right Sidebar",
      component: () => import("../views/blog/BlogRightSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-both-sidebar",
      name: "Blog Both Sidebar",
      component: () => import("../views/blog/BlogBothSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-wide-sidebar",
      name: "BlogWideSidebar",
      component: () => import("../views/blog/BlogWideSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-archive",
      name: "BlogArchive",
      component: () => import("../views/blog/BlogArchive.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-author",
      name: "BlogAuthor",
      component: () => import("../views/blog/BlogAuthor.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-category",
      name: "BlogCategory",
      component: () => import("../views/blog/BlogCategory.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-tag",
      name: "BlogTag",
      component: () => import("../views/blog/BlogTag.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/blog-tag",
      name: "BlogTag",
      component: () => import("../views/blog/BlogTag.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-standard",
      name: "PostStandard",
      component: () => import("../views/blog/PostStandard.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-left-sidebar",
      name: "PostLeftSidebar",
      component: () => import("../views/blog/PostLeftSidebar.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-header-image",
      name: "PostHeaderImage",
      component: () => import("../views/blog/PostHeaderImage.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/post-slide-show",
      name: "PostSlideShow",
      component: () => import("../views/blog/PostSlideShow.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-side-image",
      name: "PostSideImage",
      component: () => import("../views/blog/PostSideImage.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-gallery",
      name: "PostGallery",
      component: () => import("../views/blog/PostGallery.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-gallery-alternative",
      name: "PostGalleryAlternative",
      component: () => import("../views/blog/PostGalleryAlternative.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-open-gutenberg",
      name: "PostOpenGutenberg",
      component: () => import("../views/blog/PostOpenGutenberg.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-link",
      name: "PostLink",
      component: () => import("../views/blog/PostLink.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-audio",
      name: "PostAudio",
      component: () => import("../views/blog/PostAudio.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/post-video",
      name: "PostVideo",
      component: () => import("../views/blog/PostVideo.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/portfolio-tiles",
      name: "PortfolioTiles",
      component: () => import("../views/blog/PortfolioTiles.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/collage-style-1",
      name: "CollageStyle1",
      component: () => import("../views/blog/CollageStyle1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/collage-style-2",
      name: "CollageStyle2",
      component: () => import("../views/blog/CollageStyle2.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/masonry-grid",
      name: "MasonryGrid",
      component: () => import("../views/blog/MasonryGrid.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/cobble-style-1",
      name: "CobbleStyle1",
      component: () => import("../views/blog/CobbleStyle.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/cobble-style-2",
      name: "CobbleStyle2",
      component: () => import("../views/blog/CobbleStyle2.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/portfolio-thumbs-slider",
      name: "PortfolioThumbsSlider",
      component: () => import("../views/blog/PortfolioThumbsSlider.vue"),
      meta: { layout4: "layout4" },
    },
    {
      path: "/portfolio-film-strip",
      name: "PortfolioFilmStrip",
      component: () => import("../views/blog/PortfolioFilmStrip.vue"),
      meta: { layout4: "layout4" },
    },
    {
      path: "/carousel-showcase",
      name: "CarouselShowcase",
      component: () => import("../views/blog/CarouselShowcase.vue"),
      meta: { layout4: "layout4" },
    },
    {
      path: "/portfolio-split-slider",
      name: "PortfolioSplitSlider",
      component: () => import("../views/blog/PortfolioSplitSlider.vue"),
      meta: { layout4: "layout4" },
    },
    {
      path: "/portfolio-details-1",
      name: "PortfolioDetails1",
      component: () => import("../views/blog/PortfolioDetails1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/portfolio-details-2",
      name: "PortfolioDetails2",
      component: () => import("../views/blog/PortfolioDetails2.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/portfolio-details-3",
      name: "PortfolioDetails3",
      component: () => import("../views/blog/PortfolioDetails3.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/portfolio-details-4",
      name: "PortfolioDetails4",
      component: () => import("../views/blog/PortfolioDetails4.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/portfolio-details-5",
      name: "PortfolioDetails5",
      component: () => import("../views/blog/PortfolioDetails5.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/about-us",
      name: "AboutUs",
      component: () => import("../views/pages/AboutUs.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/about-me",
      name: "AboutMe",
      component: () => import("../views/pages/AboutMe.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/pricing-table",
      name: "PricingTable",
      component: () => import("../views/pages/PricingTable.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/our-gift-vouchers",
      name: "OurGiftVouchers",
      component: () => import("../views/pages/OurGiftVouchers.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/what-we-do",
      name: "WhatWeDo",
      component: () => import("../views/pages/WhatWeDo.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/faqs-1",
      name: "Faqs1",
      component: () => import("../views/pages/Faqs1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/faqs-2",
      name: "Faqs2",
      component: () => import("../views/pages/Faqs2.vue"),
      meta: { layout18: "layout18" },
    },
    {
      path: "/our-team",
      name: "OurTeam",
      component: () => import("../views/pages/OurTeam.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/contact-us-1",
      name: "ContactUs1",
      component: () => import("../views/pages/ContactUs1.vue"),
      meta: { layout4: "layout4" },
    },
    {
      path: "/contact-us-2",
      name: "ContactUs2",
      component: () => import("../views/pages/ContactUs2.vue"),
      meta: { layout5: "layout5" },
    },
    {
      path: "/contact-us-3",
      name: "ContactUs3",
      component: () => import("../views/pages/ContactUs3.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/error-1",
      name: "Error1",
      component: () => import("../views/pages/Error1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/error-2",
      name: "Error2",
      component: () => import("../views/pages/Error2.vue"),
      meta: { layout6: "layout6" },
    },
    {
      path: "/coming-soon",
      name: "ComingSoon",
      component: () => import("../views/pages/ComingSoon.vue"),
      meta: { layout6: "layout6" },
    },
    {
      path: "/under-construction",
      name: "UnderConstruction",
      component: () => import("../views/pages/UnderConstruction.vue"),
      meta: { layout6: "layout6" },
    },
    {
      path: "/banner-with-bg-color",
      name: "BannerWithBgColor",
      component: () => import("../views/pages/BannerWithBgColor.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/banner-with-image",
      name: "BannerWithImage",
      component: () => import("../views/pages/BannerWithImage.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/banner-with-video",
      name: "BannerWithVideo",
      component: () => import("../views/pages/BannerWithVideo.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/banner-with-kanbern",
      name: "BannerWithKanbern",
      component: () => import("../views/pages/BannerWithKanbern.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/banner-small",
      name: "SannerSmall",
      component: () => import("../views/pages/SannerSmall.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/banner-medium",
      name: "BannerMedium",
      component: () => import("../views/pages/BannerMedium.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/banner-large",
      name: "BannerLarge",
      component: () => import("../views/pages/BannerLarge.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/header-style-1",
      name: "HeaderStyle1",
      component: () => import("../views/pages/HeaderStyle1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/header-style-2",
      name: "HeaderStyle2",
      component: () => import("../views/pages/HeaderStyle2.vue"),
      meta: { layout7: "layout7" },
    },
    {
      path: "/header-style-3",
      name: "HeaderStyle3",
      component: () => import("../views/pages/HeaderStyle3.vue"),
      meta: { layout8: "layout8" },
    },
    {
      path: "/header-style-4",
      name: "HeaderStyle4",
      component: () => import("../views/pages/HeaderStyle4.vue"),
      meta: { layout3: "layout3" },
    },
    {
      path: "/header-style-5",
      name: "HeaderStyle5",
      component: () => import("../views/pages/HeaderStyle5.vue"),
      meta: { layout4: "layout4" },
    },
    {
      path: "/header-style-6",
      name: "HeaderStyle6",
      component: () => import("../views/pages/HeaderStyle6.vue"),
      meta: { layout9: "layout9" },
    },
    {
      path: "/header-style-7",
      name: "HeaderStyle7",
      component: () => import("../views/pages/HeaderStyle7.vue"),
      meta: { layout10: "layout10" },
    },
    {
      path: "/footer-style-1",
      name: "FooterStyle1",
      component: () => import("../views/pages/FooterStyle1.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/footer-style-2",
      name: "FooterStyle2",
      component: () => import("../views/pages/FooterStyle2.vue"),
      meta: { layout11: "layout11" },
    },
    {
      path: "/footer-style-3",
      name: "FooterStyle3",
      component: () => import("../views/pages/FooterStyle3.vue"),
      meta: { layout12: "layout12" },
    },
    {
      path: "/footer-style-4",
      name: "FooterStyle4",
      component: () => import("../views/pages/FooterStyle4.vue"),
      meta: { layout13: "layout13" },
    },
    {
      path: "/footer-style-5",
      name: "FooterStyle5",
      component: () => import("../views/pages/FooterStyle5.vue"),
      meta: { layout14: "layout14" },
    },
    {
      path: "/footer-style-6",
      name: "FooterStyle6",
      component: () => import("../views/pages/FooterStyle6.vue"),
      meta: { layout15: "layout15" },
    },
    {
      path: "/footer-style-7",
      name: "FooterStyle7",
      component: () => import("../views/pages/FooterStyle7.vue"),
      meta: { layout16: "layout16" },
    },
    {
      path: "/account-dashboard",
      name: "AccountDashboard",
      component: () => import("../views/myAccount/Dashboard.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-orders",
      name: "AccountOrders",
      component: () => import("../views/myAccount/Orders.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-order-details",
      name: "AccountOrderDetails",
      component: () => import("../views/myAccount/OrderDetails.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-order-confirmation",
      name: "OrderConfirmation",
      component: () => import("../views/myAccount/OrderConfirmation.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-downloads",
      name: "AccountDownloads",
      component: () => import("../views/myAccount/AccountDownloads.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-return-request",
      name: "AccountReturnRequest",
      component: () => import("../views/myAccount/ReturnRequest.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-return-request-detail",
      name: "AccountReturnRequestDetail",
      component: () => import("../views/myAccount/ReturnRequestDetail.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-refund-requests-confirmed",
      name: "AccountRefundRequestsConfirmed",
      component: () => import("../views/myAccount/RefundRequestsConfirmed.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/w3menu",
      name: "W3Menu",
      component: () => import("../views/W3Menu.vue"),
      meta: { layout17: "layout17" },
    },
    {
      path: "/account-profile",
      name: "AccountProfile",
      component: () => import("../views/myAccount/Profile.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-address",
      name: "AccountAddress",
      component: () => import("../views/myAccount/Address.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-shipping-methods",
      name: "AccountShippingMethods",
      component: () => import("../views/myAccount/ShippingMethods.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-payment-methods",
      name: "AccountPaymentMethods",
      component: () => import("../views/myAccount/PaymentMethods.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-review",
      name: "AccountReview",
      component: () => import("../views/myAccount/Review.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-billing-address",
      name: "AccountBillingAddress",
      component: () => import("../views/myAccount/BillingAddress.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-shipping-address",
      name: "AccountShippingAddress",
      component: () => import("../views/myAccount/AccountShippingAddress.vue"),
      meta: { layout2: "layout2" },
    },
    {
      path: "/account-cancellation-requests",
      name: "AccountCancellationRequests",
      component: () => import("../views/myAccount/CancellationRequests.vue"),
      meta: { layout2: "layout2" },
    },
  ],
});

export default router;
